export const supplementalCollections = [
  { id: "wudu", label: "أذكار الوضوء", description: "بعد الوضوء", shortcut: null },
  { id: "mosque", label: "أذكار المسجد", description: "الدخول والخروج", shortcut: null },
  { id: "home", label: "أذكار المنزل", description: "الدخول والخروج", shortcut: null },
  { id: "istikhara", label: "دعاء الاستخارة", description: "طلب الخيرة", shortcut: null },
  { id: "rain-thunder", label: "أدعية المطر والرعد", description: "مطر ورعد ورياح", shortcut: null },
  { id: "distress", label: "أدعية الكرب", description: "تفريج وطمأنينة", shortcut: null },
  { id: "ease", label: "أدعية التيسير", description: "عند تعسر الأمر", shortcut: null },
  { id: "extra-protection", label: "أدعية التحصين", description: "حفظ ووقاية", shortcut: null }
];

export const supplementalDuas = [
  {
    id: "dua-wudu-shahada",
    category: "أذكار الوضوء",
    categoryNumber: 940,
    duaNumber: 1,
    order: 1,
    text: "أشهد أن لا إله إلا الله وحده لا شريك له، وأشهد أن محمدًا عبده ورسوله",
    note: "من قالها بعد الوضوء فتحت له أبواب الجنة الثمانية يدخل من أيها شاء. رواه مسلم.",
    source: "صحيح مسلم",
    target: 1,
    kind: "dhikr",
    collectionId: "wudu",
    collectionLabel: "أذكار الوضوء",
    tags: ["wudu", "وضوء"]
  },
  {
    id: "dua-mosque-enter",
    category: "أذكار المسجد",
    categoryNumber: 941,
    duaNumber: 1,
    order: 1,
    text: "اللهم افتح لي أبواب رحمتك",
    note: "يقال عند دخول المسجد كما ثبت في صحيح مسلم.",
    source: "صحيح مسلم",
    target: null,
    kind: "dua",
    collectionId: "mosque",
    collectionLabel: "أذكار المسجد",
    tags: ["mosque", "مسجد"]
  },
  {
    id: "dua-mosque-exit",
    category: "أذكار المسجد",
    categoryNumber: 941,
    duaNumber: 2,
    order: 2,
    text: "اللهم إني أسألك من فضلك",
    note: "يقال عند الخروج من المسجد كما ثبت في صحيح مسلم.",
    source: "صحيح مسلم",
    target: null,
    kind: "dua",
    collectionId: "mosque",
    collectionLabel: "أذكار المسجد",
    tags: ["mosque", "مسجد"]
  },
  {
    id: "dua-home-enter",
    category: "أذكار المنزل",
    categoryNumber: 942,
    duaNumber: 1,
    order: 1,
    text: "بسم الله ولجنا، وبسم الله خرجنا، وعلى الله ربنا توكلنا",
    note: "يقال عند دخول المنزل، ثم يسلم على أهله. رواه أبو داود وحسنه أهل العلم.",
    source: "سنن أبي داود",
    target: null,
    kind: "dua",
    collectionId: "home",
    collectionLabel: "أذكار المنزل",
    tags: ["home", "منزل"]
  },
  {
    id: "dua-home-exit",
    category: "أذكار المنزل",
    categoryNumber: 942,
    duaNumber: 2,
    order: 2,
    text: "بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله",
    note: "يقال عند الخروج من المنزل، وقد ورد في السنن أن قائله يقال له: كفيت ووقيت.",
    source: "سنن أبي داود والترمذي",
    target: null,
    kind: "dua",
    collectionId: "home",
    collectionLabel: "أذكار المنزل",
    tags: ["home", "منزل"]
  },
  {
    id: "dua-istikhara",
    category: "دعاء الاستخارة",
    categoryNumber: 950,
    duaNumber: 1,
    order: 1,
    text: "اللهم إني أستخيرك بعلمك، وأستقدرك بقدرتك، وأسألك من فضلك العظيم، فإنك تقدر ولا أقدر، وتعلم ولا أعلم، وأنت علام الغيوب. اللهم إن كنت تعلم أن هذا الأمر خير لي في ديني ومعاشي وعاقبة أمري، فاقدره لي ويسره لي ثم بارك لي فيه، وإن كنت تعلم أن هذا الأمر شر لي في ديني ومعاشي وعاقبة أمري، فاصرفه عني واصرفني عنه، واقدر لي الخير حيث كان ثم أرضني به.",
    note: "دعاء الاستخارة كما ورد في حديث جابر رضي الله عنه: كان النبي ﷺ يعلمهم الاستخارة في الأمور كلها.",
    source: "صحيح البخاري",
    target: null,
    kind: "dua",
    collectionId: "istikhara",
    collectionLabel: "دعاء الاستخارة",
    tags: ["istikhara", "استخارة"]
  },
  {
    id: "dua-rain",
    category: "أدعية المطر والرعد",
    categoryNumber: 950,
    duaNumber: 2,
    order: 2,
    text: "اللهم صيبًا نافعًا.",
    note: "كان النبي ﷺ يقول عند رؤية المطر: اللهم صيبًا نافعًا.",
    source: "صحيح البخاري",
    target: null,
    kind: "dua",
    collectionId: "rain-thunder",
    collectionLabel: "أدعية المطر والرعد",
    tags: ["rain", "مطر"]
  },
  {
    id: "dua-after-rain",
    category: "أدعية المطر والرعد",
    categoryNumber: 950,
    duaNumber: 3,
    order: 3,
    text: "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ.",
    note: "ذكر يقال بعد نزول المطر إقرارًا بفضل الله ورحمته.",
    source: "صحيح البخاري وصحيح مسلم",
    target: null,
    kind: "dua",
    collectionId: "rain-thunder",
    collectionLabel: "أدعية المطر والرعد",
    tags: ["rain", "مطر"]
  },
  {
    id: "dua-thunder",
    category: "أدعية المطر والرعد",
    categoryNumber: 950,
    duaNumber: 4,
    order: 4,
    text: "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ.",
    note: "ورد عن عبد الله بن الزبير رضي الله عنهما أنه كان يقوله إذا سمع الرعد.",
    source: "الموطأ بإسناد صحيح إلى ابن الزبير",
    target: null,
    kind: "dua",
    collectionId: "rain-thunder",
    collectionLabel: "أدعية المطر والرعد",
    tags: ["thunder", "رعد"]
  },
  {
    id: "dua-distress",
    category: "أدعية الكرب",
    categoryNumber: 950,
    duaNumber: 5,
    order: 5,
    text: "لا إله إلا أنت سبحانك إني كنت من الظالمين.",
    note: "دعاء ذي النون عليه السلام في الكرب، وقد ورد في القرآن الكريم في سورة الأنبياء.",
    source: "القرآن الكريم، سورة الأنبياء",
    target: null,
    kind: "dua",
    collectionId: "distress",
    collectionLabel: "أدعية الكرب",
    tags: ["distress", "كرب"]
  },
  {
    id: "dua-ease",
    category: "أدعية التيسير",
    categoryNumber: 950,
    duaNumber: 6,
    order: 6,
    text: "اللهم لا سهل إلا ما جعلته سهلًا، وأنت تجعل الحزن إذا شئت سهلًا.",
    note: "دعاء نافع عند تعسر الأمر، ومعناه سؤال الله تيسير الصعب.",
    source: "حسنه جمع من أهل العلم",
    target: null,
    kind: "dua",
    collectionId: "ease",
    collectionLabel: "أدعية التيسير",
    tags: ["ease", "تيسير"]
  },
  {
    id: "dua-protection-children",
    category: "أدعية التحصين",
    categoryNumber: 950,
    duaNumber: 7,
    order: 7,
    text: "أعيذك بكلمات الله التامة من كل شيطان وهامة، ومن كل عين لامة.",
    note: "كان النبي ﷺ يعوذ بها الحسن والحسين رضي الله عنهما.",
    source: "صحيح البخاري",
    target: null,
    kind: "dua",
    collectionId: "extra-protection",
    collectionLabel: "أدعية التحصين",
    tags: ["protection", "تحصين"]
  }
];
